config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts, only: [:new, :create, :show, :edit, :update] do
    collection do
     get "search" 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many :post_tag_relations
  has_many :tags, through: :post_tag_relations
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor( 
    :text, :image,
    :id, :created_at, :updated_at,
    :tag_name
  )

  with_options presence: true do
    validates :text
    validates :image
  end

  def save
    post = Post.create(text: text, image: image)
    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save
    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end

  def update(params, post)
    post.post_tag_relations.destroy_all
    tag_name = params.delete(:tag_name)
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?
    tag.save if tag_name.present?
    post.update(params)
    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations
  has_many :posts, through: :post_tag_relations
  validates :tag_name,  uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all
  end

  def new
    @post_form = PostForm.new
  end

  def create
    @post_form = PostForm.new(post_form_params)
    if @post_form.valid? 
      @post_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    post_attributes = @post.attributes
    @post_form = PostForm.new(post_attributes)
    @post_form.tag_name = @post.tags&.first&.tag_name
  end

  def update
    @post_form = PostForm.new(post_form_params)
    @post_form.image ||= @post.image.blob
    if @post_form.valid? 
      @post_form.update(post_form_params, @post)
      redirect_to root_path
    else
      render :edit
    end
  end

  def search
    return nil if params[:keyword] == ""
    tag = Tag.where(["tag_name LIKE ?", "%#{params[:keyword]}%"])
    render json:{ keyword: tag }
  end

  private
  def post_form_params
    params.require(:post_form).permit(:text, :image, :tag_name)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TagApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post_form, url: posts_path,id: 'new_post', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="message-field">
    <%= f.text_field :text, placeholder: 'type a message' %>
  </div>
  <div class="image-field">
    <div class="click-upload">
      <%= f.file_field :image %>
    </div>
  </div>
   <div class="tag-field">
    <%= f.text_field :tag_name, placeholder: 'add tags' %>
  </div>
  <div id="search-result"></div>
  <div class="submit-btn">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/posts/_form_edit.html.erb
<%= form_with model: @post_form, url: post_path(@post), method: :patch, id: 'new_post', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="message-field">
    <%= f.text_field :text, placeholder: 'type a message' %>
  </div>
  <div class="image-field">
    <div class="click-upload">
      <%= f.file_field :image %>
    </div>
  </div>
   <div class="tag-field">
    <%= f.text_field :tag_name, placeholder: 'add tags' %>
  </div>
  <div id="search-result"></div>
  <div class="submit-btn">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>編集ページ</h3>
<%= render partial: 'form_edit' %>

app/views/posts/index.html.erb
<h3>トップページ</h3>
<h3><%= link_to '新規投稿', new_post_path%></h3>
<% @posts.each do |post| %>
  <div class="posted-content">
    <%= image_tag post.image %><br>
    <%= post.text%><br>
    <%= link_to '詳細', post_path(post.id)%>
  </div>
<% end %>

app/views/posts/new.html.erb
<h3>新規投稿ページ</h3>
<%= render partial: "form" %>

app/views/posts/show.html.erb
<h3>詳細ページ</h3>
<div class="posted-content">
  <%= image_tag @post.image %>
  <table>
    <tbody>
      <tr>
        <th>名前</th>
        <td><%= @post.text%></td>
      </tr>
      <tr>
        <th>タグ</th>
        <td><%= @post.tags&.first&.tag_name %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to '編集', edit_post_path(@post.id)%>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>